#!/bin/bash

SCRIPTS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASEPATH_DIR=$(echo $SCRIPTS_DIR | rev | cut -f2- -d/ | rev)

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

get_version () {

	cd /opt/$BASEPATH_DIR/versions/
	git rev-parse --abbrev-ref HEAD

}

get_python () {

	if [ -f /opt/$BASEPATH_DIR/versions/PYTHON ]; then
		cat /opt/$BASEPATH_DIR/versions/PYTHON
	else
		echo 3
	fi	

}

get_packagename () {

	PYTHONVERSION=$(get_python)
	echo $(echo $1 | sed -e 's/\([^.]*\)-.*/\1/' | sed "s/python$PYTHONVERSION-//g")

}


build_rpm () {
	VERSION=$(get_version)

	mkdir -p /opt/$BASEPATH_DIR/versions/logs/
	
	echo "Building Package $1, saving output to /opt/$BASEPATH_DIR/versions/logs/$1.log"
	# Legacy repo for AWX-RPM < 24.1.0: --addrepo=https://download.copr.fedorainfracloud.org/results/@copr/PyPI/epel-9-x86_64
	unbuffer mock -r epel-9-x86_64 --enable-network --addrepo /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/ --resultdir /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/ --no-clean /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/$1 --rpmbuild-opts="--nocheck" --no-cleanup-after | tee /opt/$BASEPATH_DIR/versions/logs/$1.log > /opt/$BASEPATH_DIR/versions/logs/currentbuild.log
	if ls /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.rpm 1> /dev/null 2>&1; then
		echo -e "${GREEN}Build succeeded.${NC}"
		rm -f /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.src.rpm
		cp /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.rpm /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/
		NEWPACKAGES=$((NEWPACKAGES+1))
		BUILDSTATUS=1
	else
		echo -e "${RED}Build failed, check logs to correct.${NC}"
		BUILDSTATUS=0
	fi

	createrepo_c /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/ >> /opt/$BASEPATH_DIR/versions/logs/$1.log 2>&1
	rm -f /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/* >> /opt/$BASEPATH_DIR/versions/logs/$1.log 2>&1
	mock -r epel-9-x86_64 --clean >> /opt/$BASEPATH_DIR/versions/logs/$1.log 2>&1
	/opt/$BASEPATH_DIR/scripts/changeversion save $BUILDSTATUS $1 
}
