#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)
PYTHONBUILD=$(get_python)

DATE=$(date +"%a %b %d %Y %r %Z %z")

PACKAGEVERSION=$1

echo "Generating source and build for receptor version: $PACKAGEVERSION for version: $VERSION"

wget -O /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/SOURCES/receptor-$PACKAGEVERSION.tar.gz https://github.com/ansible/receptor/archive/refs/tags/v$PACKAGEVERSION.tar.gz

cp /opt/$BASEPATH_DIR/templates/receptor-temp.spec /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤VERSION¤|$PACKAGEVERSION|g" /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s/%setup/%setup -n receptor-%{version}/g" /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤DATE¤|$DATE|g" /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤PYTHON3PKGVERSION¤|$PYTHONBUILD|g" /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec

rpmbuild -bs --define "_topdir /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/" /opt/$BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec

mock -r epel-9-x86_64 --enable-network --addrepo /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS --resultdir /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/ --no-clean /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/awx-receptor-$PACKAGEVERSION-1.el9.src.rpm --rpmbuild-opts="--nocheck" --no-cleanup-after
rm -f /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.src.rpm
cp /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.rpm /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/
createrepo_c /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/
rm -f /opt/$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*
mock -r epel-9-x86_64 --clean

